apiVersion: v1 
kind: Secret 
metadata: 
  name: kmcs-ontap-secret 
  Type: Opaque 
stringData: 
  username: vsadmin 
  password: admin123 

--- 

apiVersion: trident.netapp.io/v1 
kind: TridentBackendConfig 
metadata: 
  name: kmcs-ontap-nas-prod
spec: 
  version: 1 
  storageDriverName: ontap-nas-economy 
  managementLIF: <netapp-mgmt-ip>   
  dataLIF: <nfs-lif-ip> 
  svm: openshift_svm 
  limitAggregateUsage: 50% 
  autoExportCIDRs: 
    -<10.0.x.x/24> 
  autoExportPolicy: true 
  credentials: 
    name: kmcs-ontap-secret 