# This config is no longer needed as we are not using NFS bridge
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: nncp-nfs-bridge-static-ip-rhpoc-us02-wrkr02
spec:
  # Apply this policy only to specific nodes (e.g., worker nodes)
  # Add label name=nodename for each of the worker nodes to ensure the nodeselector assigns the policy to the respective node
  nodeSelector:
    name: "rhpoc-us02-wrkr02"
  desiredState:
    interfaces:
      # Configuration for the physical interface (port of the bridge)
      - name: eno8
        type: ethernet
        state: up
        controller: br-nfs
      # Configuration for the new Linux bridge interface
      - name: br-nfs
        description: Linux bridge for NFS storage network
        type: linux-bridge
        state: up
        ipv4:
          # Use static IP assignment
          enabled: true
          dhcp: false
          address:
            # Replace with your specific static IP and prefix length
            - ip: 10.0.1.72
              prefix-length: 24
        bridge:
          options:
            # Disable Spanning Tree Protocol (STP) if not needed
            stp:
              enabled: false
          port:
            - name: eno8
    # Optional: Configure DNS if necessary for the NFS network
    # dns-resolver:
    #   config:
    #     server:
    #       - 8.8.8.8
