# Collected this script from Cisco Validated Design for OpenShift Linux Bridge
apiVersion: nmstate.io/v1 
kind: NodeNetworkConfigurationPolicy 
metadata: 
  name: nncp-br-vm-ovs-policy
spec: 
  nodeSelector: 
    # Use specific node name if the policy is for that node
    # name: "rhpoc-us02-wrkr01"
    # Use node-role to push the policy to all the worker nodes. Make this change after adding eno9 to all the worker nodes
    node-role: "worker"
  desiredState: 
    interfaces: 
      - name: br-vm-network 
        description: VM Traffic bridge with eno6 as a port
        type: ovs-bridge 
        state: up
        mtu: 9000
        ipv4: 
          enabled: false 
        ipv6: 
          enabled: false 
        bridge:
          allow-extra-patch-ports: true
          options: 
            stp: 
              enabled: false 
          port: 
            - name: eno9
    ovn:
      bridge-mappings:
              - bridge: br-vm-network
                localnet: defcon-vlan1007-net
                state: present
              - bridge: br-vm-network
                localnet: reflex-vlan1008-net
                state: present