apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: win2019-iso-shared
  namespace: default
  annotations:
    description: "Shared Windows Server 2019 ISO - used by all VMs"
spec:
  pvc:
    accessModes:
    - ReadOnlyMany              # ← ReadOnlyMany allows multiple VMs to use it!
    resources:
      requests:
        storage: 15Gi
    storageClassName: kmcs-ontap-nas1-class
  source:
    http:
      url: "http://10.0.0.12/Upload-Site/SW_DVD9_Win_Server_STD_CORE_2019_1809.19_64Bit_English_DC_STD_MLF_X23-31944.iso"

---
# create Win11 CD ROM
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: fin-win11-iso-shared
  namespace: finance #Set the appropriate namespace here
  annotations:
    description: "Shared Windows 11 ISO - used by all VMs"
spec:
  pvc:
    accessModes:
    - ReadOnlyMany              # ← ReadOnlyMany allows multiple VMs to use it!
    resources:
      requests:
        storage: 15Gi
    storageClassName: kmcs-ontap-nas1-class
  source:
    http:
      url: "http://10.0.0.12/Upload-Site/SW_DVD9_Win_Pro_11_23H2_64BIT_English_Pro_Ent_EDU_N_MLF_X23-59562.iso"

---
# create Win2025 CD ROM
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: fin-win2025-iso-shared
  namespace: finance #Set the appropriate namespace here
  annotations:
    description: "Shared Windows 2025 ISO - used by all VMs"
spec:
  pvc:
    accessModes:
    - ReadOnlyMany              # ← ReadOnlyMany allows multiple VMs to use it!
    resources:
      requests:
        storage: 15Gi
    storageClassName: kmcs-ontap-nas1-class
  source:
    http:
      url: "http://10.0.0.12/Upload-Site/SW_DVD9_Win_Server_STD_CORE_2025_24H2_64Bit_English_DC_STD_MLF_X23-81891.iso"