# If you want to create both secret and the trident backend then run the entire defintion
# if you want to separately create the secret and then create the trident then run the below two defitions separately
apiVersion: v1 
kind: Secret 
metadata: 
  name: comp-ontap-secret-nas1 
  Type: Opaque
stringData: 
  username: vsadmin #SVM admin only
  password: xxx

---

apiVersion: trident.netapp.io/v1 
kind: TridentBackendConfig
metadata: 
  name: comp-ontap-nas1-prod
spec: 
  version: 1 
  storageDriverName: ontap-nas 
  managementLIF: REDHATPOC-MGMT.rhpoc.int # 10.100.0.210 is the mgmt lif  
  dataLIF: REDHATPOCHET.rhpoc.int # 10.100.1.16, 10.100.1.17, 10.100.0.21, 10.100.0.22 are the data lifs associated with this DNS zone
  svm: REDHATPOCHET
  #limitAggregateUsage: 50% 
  autoExportCIDRs: 
    - 10.100.1.0/24
  autoExportPolicy: true 
  credentials: 
    # Secret reference to "trident-backend-ontap-nas1-secret.yaml"
    name: comp-ontap-secret-nas1