# Collected this script from Cisco Validated Design for OpenShift Linux Bridge
apiVersion: nmstate.io/v1 
kind: NodeNetworkConfigurationPolicy 
metadata: 
  name: nncp-br-vm-network-policy 
spec: 
  nodeSelector: 
    node-role.kubernetes.io/worker: '' 
  desiredState: 
    interfaces: 
      - name: br-vm-network 
        description: Linux bridge with eno9 as a port 
        type: linux-bridge 
        state: up 
        ipv4: 
          enabled: false 
        ipv6: 
          enabled: false 
        bridge: 
          options: 
            stp: 
              enabled: false 
          port: 
            - name: eno9 