# To create a schedule to rmove older snapshots leaving two latest copies of snapshots for all VMs in finance namespace.
apiVersion: batch/v1
kind: CronJob
metadata:
  name: vm-finance-snapshot-cleanup
  namespace: finance
spec:
  schedule: "0 23 * * *"  # Run at 11 PM daily (after snapshot creation)
  timeZone: "America/New_York"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          serviceAccountName: vm-finance-snapshot-sa
          restartPolicy: Never
          containers:
            - name: cleanup
              image: quay.io/openshift/origin-cli:latest
              command: ["/bin/bash", "-c"]
              args:
                - |
                  set -euo pipefail
                  
                  echo "=========================================="
                  echo "Snapshot Cleanup Job Started: $(date)"
                  echo "Namespace: finance"
                  echo "Retention: Keep last 2 snapshots per VM"
                  echo "=========================================="
                  
                  RETENTION_COUNT=2
                  TOTAL_DELETED=0
                  TOTAL_KEPT=0
                  
                  # Get all VMs in the namespace
                  VMS=$(oc get vm -n finance -o jsonpath='{.items[*].metadata.name}')
                  
                  if [ -z "$VMS" ]; then
                    echo "No VMs found in finance namespace"
                    exit 0
                  fi
                  
                  echo "Processing snapshots for VMs: $VMS"
                  echo "=========================================="
                  
                  for vm in $VMS; do
                    echo "Processing VM: ${vm}"
                    
                    # Get all snapshots for this VM, sorted by creation timestamp (oldest first)
                    SNAPSHOTS=$(oc get vmsnapshot -n finance \
                      --sort-by=.metadata.creationTimestamp \
                      -o jsonpath="{range .items[?(@.spec.source.name=='${vm}')]}{.metadata.name}{'\n'}{end}")
                    
                    if [ -z "$SNAPSHOTS" ]; then
                      echo "  No snapshots found for ${vm}"
                      continue
                    fi
                    
                    # Count snapshots
                    SNAPSHOT_ARRAY=($SNAPSHOTS)
                    TOTAL_SNAPSHOTS=${#SNAPSHOT_ARRAY[@]}
                    
                    echo "  Found ${TOTAL_SNAPSHOTS} snapshot(s) for ${vm}"
                    
                    if [ $TOTAL_SNAPSHOTS -le $RETENTION_COUNT ]; then
                      echo "  ✓ Keeping all ${TOTAL_SNAPSHOTS} snapshot(s) (within retention limit)"
                      TOTAL_KEPT=$((TOTAL_KEPT + TOTAL_SNAPSHOTS))
                    else
                      # Calculate how many to delete
                      TO_DELETE=$((TOTAL_SNAPSHOTS - RETENTION_COUNT))
                      echo "  Deleting ${TO_DELETE} old snapshot(s), keeping last ${RETENTION_COUNT}"
                      
                      # Delete old snapshots (keeping the last RETENTION_COUNT)
                      for ((i=0; i<$TO_DELETE; i++)); do
                        SNAPSHOT_NAME="${SNAPSHOT_ARRAY[$i]}"
                        echo "    Deleting: ${SNAPSHOT_NAME}"
                        
                        if oc delete vmsnapshot ${SNAPSHOT_NAME} -n finance; then
                          echo "    ✓ Deleted: ${SNAPSHOT_NAME}"
                          TOTAL_DELETED=$((TOTAL_DELETED + 1))
                        else
                          echo "    ✗ Failed to delete: ${SNAPSHOT_NAME}"
                        fi
                      done
                      
                      TOTAL_KEPT=$((TOTAL_KEPT + RETENTION_COUNT))
                    fi
                    echo "  ---"
                  done
                  
                  echo "=========================================="
                  echo "Cleanup Job Summary:"
                  echo "  Total VMs processed: $(echo $VMS | wc -w)"
                  echo "  Snapshots deleted: ${TOTAL_DELETED}"
                  echo "  Snapshots retained: ${TOTAL_KEPT}"
                  echo "  Completed at: $(date)"
                  echo "=========================================="
                  
                  exit 0