apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: win2019-vm4
  namespace: default
  labels:
    app: win2019-vm4
    kubevirt.io/vm: win2019-vm4
spec:
  runStrategy: Halted
  dataVolumeTemplates:
    - metadata:
        name: win2019-vm4-rootdisk
      spec:
        pvc:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 64Gi
          storageClassName: kmcs-ontap-nas1-class
        source:
          blank: {}
    - metadata:
        name: win2019-installation-cdrom
      spec:
        pvc:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 15Gi
          storageClassName: kmcs-ontap-nas1-class
        source:
          http:
            url: "http://10.0.0.12/Upload-Site/SW_DVD9_Win_Server_STD_CORE_2019_1809.19_64Bit_English_DC_STD_MLF_X23-31944.iso"    # ← Put your URL here
  template:
    metadata:
      labels:
        kubevirt.io/vm: win2019-vm
    spec:
      domain:
        cpu:
          cores: 4
          sockets: 1
          threads: 1
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
              bootOrder: 1
            - name: installation-cdrom
              cdrom:
                bus: sata
              bootOrder: 2
            - name: windows-drivers-disk
              cdrom:
                bus: sata
          interfaces:
            - name: default
              masquerade: {}
              model: virtio
          channels:
            - name: qemu-guest-agent
              type: unix
        firmware:
          bootloader:
            bios: {}
        machine:
          type: q35
        resources:
          requests:
            memory: 8Gi
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          dataVolume:
            name: win2019-rootdisk
        - name: installation-cdrom
          dataVolume:
            name: win2019-installation-cdrom
        - name: windows-drivers-disk
          containerDisk:
            image: registry.redhat.io/container-native-virtualization/virtio-win